version: '3.7'

services:
  postgres:
    container_name: treeShopCourse
    image: postgres:14
    ports:
      - ${POSTGRES_PORT:?err}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_PORT=${POSTGRES_PORT:?err}
      - POSTGRES_HOST=${POSTGRES_HOST:?err}
    volumes:
      - './volumes/postgres:/var/lib/postgresql'

  redis:
    image: redis:alpine
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '8379:6379'
