export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ERROR_ROUTE = '/ERROR'
export const AUTH_ROUTE = '/Auth'

export const ACCOUNT_ROUTE = '/Account'
export const GROUP_ROUTE = '/Group'
export const TABLE_ROUTE = '/Timetable'
export const MATERIALS_ROUTE = '/Workmaterials'
export const REQUEST_ROUTE = '/Requests'
export const SUPPORT_ROUTE = '/SupportUser'
export const ADMIN_SUPPORT_ROUTE = '/AdminSupport'
export const NONAME_TOVARI_ROUTE ='/TovariNoname'
export const USERS_TOVARI_ROUTE ='/TovariUsers'

